swagger: "2.0"
info:
    title: poc Service
    description: foo bar
    version: 0.0.1
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /todos/{id}:
        get:
            tags:
                - poc
            summary: get poc
            operationId: poc#get
            parameters:
                - name: id
                  in: path
                  description: ID of the item
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/HTTPConfig'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - message
            schemes:
                - http
definitions:
    HTTPConfig:
        title: HTTPConfig
        type: object
        properties:
            host:
                type: string
                description: The host
                example: Tempore incidunt fugiat ipsum tenetur.
            port:
                type: integer
                description: The port number
                example: 2681370607926342447
                format: int64
        example:
            host: Qui laudantium pariatur neque.
            port: 6471708337231520368
    NotFoundError:
        title: NotFoundError
        type: object
        properties:
            message:
                type: string
                example: Voluptatibus et accusantium ut.
        example:
            message: In veritatis aut est placeat.
        required:
            - message
